---

- name: Manage icinga2 api-users.conf
  template:
    src: api-users.conf.j2
    dest: /etc/icinga2/conf.d/api-users.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0640
  notify: Test config before restart icinga 2
